# Generated by Django 4.2.2 on 2024-10-06 11:16

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Procedures",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Введите название процедуры",
                        max_length=100,
                        unique=True,
                        verbose_name="Название процедуры",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Введите описание процедуры",
                        null=True,
                        verbose_name="Описание процедуры",
                    ),
                ),
                (
                    "price",
                    models.IntegerField(
                        default=100,
                        help_text="Введите цену процедуры",
                        validators=[django.core.validators.MinValueValidator(100)],
                        verbose_name="Цена процедуры",
                    ),
                ),
            ],
            options={
                "verbose_name": "Процедура",
                "verbose_name_plural": "Процедуры",
            },
        ),
        migrations.CreateModel(
            name="Doctors",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        help_text="Введите имя доктора",
                        max_length=50,
                        verbose_name="Имя",
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        help_text="Введите фамилию доктора",
                        max_length=50,
                        verbose_name="Фамилия",
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        help_text="Загрузите фотографию доктора",
                        null=True,
                        upload_to="doctor_photos",
                        verbose_name="Фотография",
                    ),
                ),
                (
                    "specialization",
                    models.CharField(
                        help_text="Введите специализацию доктора",
                        max_length=100,
                        verbose_name="Специализация",
                    ),
                ),
                (
                    "degree",
                    models.CharField(
                        help_text="Введите ученую степень доктора",
                        max_length=100,
                        verbose_name="Ученая степень",
                    ),
                ),
                (
                    "procedures",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Выберите процедуры, которые доктор может провести",
                        to="medicine.procedures",
                        verbose_name="Процедуры",
                    ),
                ),
            ],
            options={
                "verbose_name": "Доктор",
                "verbose_name_plural": "Доктора",
            },
        ),
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "appointment_datetime",
                    models.DateTimeField(
                        help_text="Выберите дату и время записи",
                        verbose_name="Дата и время записи",
                    ),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        help_text="Выберите доктора для записи",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="medicine.doctors",
                        verbose_name="Доктор",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        help_text="Выберите пациента для записи",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пациент",
                    ),
                ),
                (
                    "procedure",
                    models.ForeignKey(
                        help_text="Выберите процедуру для записи",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="medicine.procedures",
                        verbose_name="Процедура",
                    ),
                ),
            ],
            options={
                "verbose_name": "Запись на приём",
                "verbose_name_plural": "Записи на приём",
            },
        ),
    ]
