# Generated by Django 4.2.2 on 2024-09-29 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medicine", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="doctors",
            name="medicine",
        ),
        migrations.AddField(
            model_name="doctors",
            name="medicine",
            field=models.ManyToManyField(
                blank=True,
                help_text="Выберите процедуры, которые доктор может провести",
                null=True,
                to="medicine.medicine",
                verbose_name="Процедуры",
            ),
        ),
    ]
