# Generated by Django 4.2.2 on 2024-10-06 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medicine", "0002_feedback"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="feedback",
            options={"verbose_name": "Отзыв", "verbose_name_plural": "Отзывы"},
        ),
        migrations.AlterField(
            model_name="feedback",
            name="text",
            field=models.TextField(verbose_name="Отзыв"),
        ),
    ]
