# Generated by Django 4.2.2 on 2024-09-29 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medicine", "0002_remove_doctors_procedures_doctors_procedures"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doctors",
            name="medicine",
            field=models.ManyToManyField(
                blank=True,
                help_text="Выберите процедуры, которые доктор может провести",
                to="medicine.medicine",
                verbose_name="Процедуры",
            ),
        ),
    ]
